version: "3.8"

services:
  # HTTP Server: NginX 1.19.1 on Alpine 3.12
  http:
    image: nginx:1.19.1
    container_name: alp-http
    links:
      - app
    ports:
      - 8080:80
    restart: always
    volumes:
      - ".:/www"
      - "./docker/http/default.conf:/etc/nginx/conf.d/default.conf"

  # App: PHP FPM 7.4.8 and NodeJS 14.5.0 on Alpine 3.12
  app:
    image: alp-app
    build:
      context: .
    container_name: alp-app
    restart: always
    volumes:
      - ".:/www"